version: '3'

services:
  db:
    image: postgres:16-alpine
    container_name: portfolio-postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=portfolio
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - portfolio-network
  redis:
    image: redis
    container_name: portfolio-redis
    ports:
      - 6380:6379
    volumes:
      - redis:/data
    networks:
      - portfolio-network

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    container_name: portfolio-redis-http
    ports:
      - 8080:80
    environment:
      SRH_MODE: env
      SRH_TOKEN: portfolio
      SRH_CONNECTION_STRING: redis://redis:6379
    networks:
      - portfolio-network
    depends_on:
      - redis

volumes:
  db:
  redis:

networks:
  portfolio-network:
    driver: bridge
